// This only looks at "actively developed packages", which we defiend
// as having published in the last 180 days.
TiNuGetPackageDetailsStaging
| where todatetime(Published) > ago(180d)
        and Authors !contains 'Microsoft'
| join kind=inner (TiPkgToBinStaging) on PkgHash
| where ContainerPath startswith 'lib/'
| extend TargetFramework = iif(ContainerPath startswith 'lib/netstandard1', 'ns1x', iff(ContainerPath startswith 'lib/netstandard2', 'ns2', iff(ContainerPath startswith 'lib/net4', 'netfx4', iff(ContainerPath startswith 'lib/portable', 'portable', 'other'))))
| summarize NS2Count=countif(TargetFramework == 'ns2'), NS1Count=countif(TargetFramework == 'ns1x') by Id
| summarize NSSupport=countif((NS1Count +NS2Count) > 0), Total=count()
