TiNuGetPackageDetailsStaging
| join kind=inner (TiNuGetPackageDetailsStaging
                   | join kind=inner (TiPkgToBinStaging) on PkgHash
                   | where ContainerPath startswith "lib/"
                   | summarize Authors=any(Authors), Id=any(Id) by PkgHash) on PkgHash
| where Authors !contains 'Microsoft'
| join kind=inner (TiPkgToBinStaging) on PkgHash
| extend TargetFramework = iif(ContainerPath startswith 'lib/netstandard1', 'ns1x', iff(ContainerPath startswith 'lib/netstandard2', 'ns2', iff(ContainerPath startswith 'lib/net4', 'netfx4', iff(ContainerPath startswith 'lib/portable', 'portable', 'other'))))
| summarize NS2Count=countif(TargetFramework == 'ns2'), NS1Count=countif(TargetFramework == 'ns1x') by Id, Version, Published=todatetime(Published)
| where NS1Count > 0 or NS2Count > 0
| summarize ConversionDate=min(Published) by Id
| summarize ConvertedPackages=count() by bin_at(ConversionDate, 7d, now())
| order by ConversionDate asc


TiNuGetPackageDetailsStaging
| join kind=inner (TiNuGetPackageDetailsStaging
                   | join kind=inner (TiPkgToBinStaging) on PkgHash
                   | where ContainerPath startswith "lib/"
                   | summarize Authors=any(Authors), Id=any(Id) by PkgHash) on PkgHash
| where Authors !contains 'Microsoft'
| join kind=inner (TiPkgToBinStaging) on PkgHash
| extend TargetFramework = iif(ContainerPath startswith 'lib/netstandard1', 'ns1x', iff(ContainerPath startswith 'lib/netstandard2', 'ns2', iff(ContainerPath startswith 'lib/net4', 'netfx4', iff(ContainerPath startswith 'lib/portable', 'portable', 'other'))))
| summarize NS2Count=countif(TargetFramework == 'ns2'), NS1Count=countif(TargetFramework == 'ns1x') by Id
| summarize NSSupport=countif((NS1Count +NS2Count) > 0), Total=count()