<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Microsoft.DotNetBlog</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="0.28.0" />
    <PackageReference Include="Markdig" Version="0.21.1" />
    <PackageReference Include="YamlDotNet" Version="8.1.2" />
  </ItemGroup>
  
</Project>
