<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>Microsoft.DotNetBlog</RootNamespace>
    <Nullable>Enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Humanizer.Core" Version="2.11.10" />
    <PackageReference Include="Spectre.Console" Version="0.41.0" />
  </ItemGroup>

</Project>
