FROM microsoft/dotnet:2.2-sdk AS builder
WORKDIR /build
COPY . .

RUN dotnet publish -c release -o /publish-output

# Restore with `-r linux-x64` so that the runtime package that contains crossgen is downloaded
RUN dotnet restore -r linux-x64
RUN mkdir /temporary
RUN cp `find ~/.nuget/packages -name crossgen` /temporary

FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR /app
COPY --from=builder /publish-output .

# crossgen is needed by the perfcollect script
# perfcollect expects to find crossgen along side libcoreclr.so
COPY --from=builder /temporary/crossgen $(dirname `find /usr/share/dotnet/ -name libcoreclr.so`)

# add whatever tools you want here
RUN apt-get update \
    && apt-get install -y \
       linux-tools \
       lttng-tools liblttng-ust-dev \
       zip \
       curl \
       binutils \
       procps \
#      gdb \
#      strace \
#      tcpdump \
#      sysstat \
#      emacs-nox \
#      vim \
       htop \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /tools \
    && cd /tools \
    && curl -OL http://aka.ms/perfcollect \
    && chmod a+x perfcollect

WORKDIR /tools
