name: Build Tools

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - '**.cs'
    - '**.csproj'
  pull_request:
    branches: [ "main" ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build:

    name: Build Tools
    runs-on: ubuntu-latest

    steps:
    - name: Get Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: dotnet build
      run: dotnet build "tools/blog-tools.sln"