name: Update Planner

on:
  pull_request:
    types: [opened, synchronize, closed, reopened]

jobs:
  update-planner:
    runs-on: ubuntu-latest
    steps:

    - name: Clone repo with full history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # We need the full history in order to figure
                       # out which posts were pushed.

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore
      run: dotnet restore tools/blog-get-post/blog-get-post.csproj

    - name: Build
      run: dotnet build tools/blog-get-post/blog-get-post.csproj --configuration Release --no-restore --nologo

    - name: Get blog post metadata
      id: get-post
      run: dotnet run --project tools/blog-get-post/blog-get-post.csproj

    - name: Update planner
      if: ${{ steps.get-post.outputs.title != '' }}
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.LOGIC_APPS_URL }}
        data: | 
          {
            "post": {
              "pull_request_number": "${{ steps.get-post.outputs.pull_request_number }}",
              "pull_request_is_closed": ${{ steps.get-post.outputs.pull_request_is_closed }},
              "pull_request_is_merged": ${{ steps.get-post.outputs.pull_request_is_merged }},
              "microsoft_alias": "${{ steps.get-post.outputs.alias }}",
              "desired_publication_date": "${{ steps.get-post.outputs.date }}",
              "category" : ".NET",
              "post_title": "${{ steps.get-post.outputs.title }}"
            }
          }
