name: Validate

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
 
    - name: Clone repo with full history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # We need the full history in order to figure
                       # out which files we need to validate.

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore
      run: dotnet restore tools/blog-tools.sln

    - name: Build
      run: dotnet build tools/blog-tools.sln --configuration Release --no-restore --nologo

    - name: Validate
      run: dotnet run --project tools/blog-validate/blog-validate.csproj -- . --categories categories.txt --base-ref $GITHUB_BASE_REF --ref $GITHUB_SHA
