name: Validate

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore tools/blog-tools.sln
    - name: Build
      run: dotnet build tools/blog-tools.sln --configuration Release --no-restore --nologo
    - name: Validate
      run: dotnet run --project tools/blog-validate/blog-validate.csproj -- . --base-ref {{ GITHUB_BASE_REF }} --ref {{ GITHUB_SHA }}
